config/routes.rb
Rails.application.routes.draw do

  # navigation
  root 'navigation#homepage'

  scope "/:locale" do
    get 'questions' => 'navigation#questions'

    # for activation
    get 'account_activation/:token/activate', to: 'access#account_activation',
                                              as: 'activation'
    get 'activation_form', to: 'access#activation_form', as: 'activation_form'
    post 'create_activation', to: 'access#create_activation',
                              as: 'create_activation'

    # for password reset
    get 'account_activation/:token/reset', to: 'access#reset_password',
                                              as: 'reset_password'
    get 'reset_password_form', to: 'access#reset_password_form',
                               as: 'reset_password_form'
    post 'create_reset_link', to: 'access#create_reset_link',
                              as: 'create_reset_link'

    # for login
    get 'login_form' => 'access#login_form'
    post 'create_session' => 'access#create_session'
    delete 'destroy_session' => 'access#destroy_session'

    # for sending photos
    get 'photo/:id/:type/get', to: 'photos#send_photo', as: 'get_photo'
	  get 'humans/:id/avatar', to: 'humans#send_avatar', as: 'avatar'

    resources :humans

    resources :photo_galleries, shallow: true do
      resources :photos, except: :show
    end

    resources :photos, only: :show do
      resources :comments, only: [:create]
    end

    resources :comments, only: [:destroy]
	  resources :chats, only: [:show, :index, :create]

  end

end

app/models/human.rb
# Just a human
class Human < ActiveRecord::Base
  include SharedModelMethods

  has_many :photo_galleries, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :chats, dependent: :destroy

  before_save { email.downcase! }
  before_destroy :delete_folder

  #  mount_uploader :avatar, ForAvatarUploader

  VALID_EMAIL_BEFORE_DOG = '\A[a-z\d]+((\.|-)[a-z\d]+)*'
  VALID_EMAIL_AFTER_DOG = '[a-z\d]+((\.|-)[a-z\d]+)*\z'
  DOG = '@'
  FULL_EMAIL = Regexp.new(VALID_EMAIL_BEFORE_DOG + DOG +
                          VALID_EMAIL_AFTER_DOG, 'i')

  validates :name, presence: true, length: { maximum: 48 }
  validates :email, length: { maximum: 100 },
                    format: { with: FULL_EMAIL },
                    uniqueness: { case_sensitive: false }

  has_secure_password validations: false
  validates :password, length: { minimum: 8 }, confirmation: true, on: :create
  validates :password, confirmation: true, length: { minimum: 8 },
                       if: :password_present?, on: :update

  def admin?
    if access == 'I am admin!'
      return true
    else
      return false
    end
  end

  private

  # For has_secure_password validations: false and validation at all.
  def password_present?
    !password.nil? || password_confirmation != ''
  end

  def delete_folder
    FileUtils.rm_rf "#{Rails.root}/private/photo_galleries/human_#{id}"
    FileUtils.rm_rf "#{Rails.root}/private/avatars/human_#{id}"
  end
end

app/controllers/humans_controller.rb
# Just a human controller
class HumansController < ApplicationController
  before_action :human_only
  skip_before_action :human_only, only: [:new, :create]

  def show
    @human = Human.find_by('id = ?', params[:id]) # looks securely
    return if @human
    flash[:alert] = t(:no_id)
    redirect_to root_path
  end

  def send_avatar
    @human = Human.find_by('id = ?', params[:id]) # looks securely
    if !@human
      flash[:alert] = t(:no_id)
      redirect_to root_path
    else
      avatar_path = Rails.root.to_s + @human.avatar
      send_file avatar_path, x_sendfile: true
    end
  end

  def index
    @humans = Human.numbering(params[:list], 25, 5) # numbering looks securely
  end

  def new
    if !current_human
      @human = Human.new
    else
      flash[:alert] = t(:must_be_logged_out)
      redirect_to root_path
    end
  end

  def create
    if !current_human
      @human = Human.new(attributes) # this is handled by model validations
      if @human && @human.save

        dir = "private/avatars/human_#{@human.id}"
        unless File.exist?(Rails.root.join(dir))
          FileUtils.mkdir_p(Rails.root.join(dir), mode: 0700)
        end

        MiniMagick::Tool::Convert.new do |convert|
          convert << "#{Rails.root}/public/Default_Cover/Default_Avatar.png"
          convert << "#{Rails.root}/" + dir + '/avatar.png'
        end

        @human.avatar = "/private/avatars/human_#{@human.id}/avatar.png"

        # Creating activation token
        begin
          token = SecureRandom.urlsafe_base64
          @human.activation_token = BCrypt::Password.create(token)
        end while Human.exists?(activation_token: @human.activation_token)
        @human.activation_request_at = DateTime.now

        if @human.save

          HumanMailer.account_activation(@human, token).deliver_now

          flash[:message] = t(:new_profile)
          redirect_to root_path
        else
          render 'new'
        end
      else
        render 'new'
      end
    else
      flash[:alert] = t(:must_be_logged_out)
      redirect_to root_path
    end
  end

  def edit
    @human = Human.find_by('id = ?', params[:id]) # looks securely
    if @human && (@human.id == current_human.id || current_human.admin?)
      render 'edit'
    else
      flash[:alert] = t(:restrict_to_change_profile)
      redirect_to root_path
    end
  end

  def update
    @human = Human.find_by('id = ?', params[:id]) # looks securely

    if @human && (@human.id == current_human.id || current_human.admin?)

      # if new avatar
      if file = file_attribute # looks securely
        dir = "private/avatars/human_#{@human.id}/"
        file_path = Rails.root.join(dir, 'avatar.png')
        @human.avatar = '/' + dir + 'avatar.png'

        # Creating folder
        unless File.exist?(Rails.root.join(dir))
          FileUtils.mkdir_p(Rails.root.join(dir), mode: 0700)
        end

        # Convert uploaded file to ".png"
        MiniMagick::Tool::Convert.new(false) do |convert|
          convert << file.path # questionable place
          convert << '-resize'
          convert << '200x200'
          convert << file_path
        end
        @human.save(validate: false)
      end

      # Avatar rotation.
      if !params[:rotate_avatar].blank? &&
         params[:rotate_avatar] != 'nope' &&
         !file
        avatar_rotation avatar_path: @human.avatar,
                        rotation: params[:rotate_avatar] # looks securely
      end

      # Checking for errors
      if attributes
        @human.update_attributes(attributes) # looks securely
        if @human.errors.any?
          render 'edit'
        else
          flash[:message] = t(:successful_update)
          redirect_to human_path(@human.id)
        end
      else
        flash[:alert] = t(:no_data)
        redirect_to root_path
      end

    else
      flash[:alert] = t(:restrict_to_change_profile)
      redirect_to root_path
    end
  end

  def destroy
    if current_human.admin?
      @human = Human.find_by('id = ?', params[:id]) # looks securely
      if @human && @human.id != current_human.id && @human.destroy
        flash[:message] = @human.name + t(:deleted)
        redirect_to humans_path
      else
        flash[:alert] = t(:delete_profile_problem)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:nope)
      redirect_to root_path
    end
  end

  private

  def avatar_rotation(hash = {})
    full_path = "#{Rails.root}#{hash[:avatar_path]}"
    MiniMagick::Tool::Convert.new do |convert|
      convert << full_path
      convert << '-rotate'
      convert << '90' if hash[:rotation] == 'right' # looks securely
      convert << '-90' if hash[:rotation] == 'left' # looks securely
      convert << '180' if hash[:rotation] == 'upside_down' # looks securely
      convert << full_path
    end
  end

  def attributes
    return if params[:human].blank? || !params[:human].is_a?(Hash)
    params.require(:human).permit(:name,
                                  :email,
                                  :password,
                                  :password_confirmation)
  end

  def file_attribute
    return if params[:human].blank? || !params[:human].is_a?(Hash)
    params.require(:human).permit(:avatar)[:avatar]
  end
end

app/helpers/humans_helper.rb
# HumansHelper
module HumansHelper
end

app/views/humans/edit.html.erb
<%= form_for(@human, html: {multipart: true, class: "plain_form"}) do |f| %>

  <%= render partial: 'shared/form_errors', locals: { object: @human } %>

  <div class = "avatar_block">

    <div class = "avatar_photo_block">
      <%= image_tag avatar_path(@human.id), class: "avatar_photo" %>
    </div>

    <div class = "avatar_rotation_block">
      <%= radio_button_tag :rotate_avatar, 'nope', true,
                                                   class: "radio_button" %>

      <%= label_tag :rotate_avatar_nope, class: "radio_button_label" do %>
        <div class = "radio_button_image">
        </div>
        <div class = "radio_button_text">
          <%= t(:do_not_rotate) %>
        </div>
      <% end %>

      <%= radio_button_tag :rotate_avatar, "left", false,
                                                   class: "radio_button" %>

      <%= label_tag :rotate_avatar_left, class: "radio_button_label" do %>
        <div class = "radio_button_image">
        </div>
        <div class = "radio_button_text">
          <%= t(:turn_left) %>
        </div>
      <% end %>
                                    
      <%= radio_button_tag :rotate_avatar, 'right', false,
                                                    class: "radio_button" %>

      <%= label_tag :rotate_avatar_right, class: "radio_button_label" do %>
        <div class = "radio_button_image">
        </div>
        <div class = "radio_button_text">
          <%= t(:turn_right) %>
        </div>
      <% end %>

      <%= radio_button_tag :rotate_avatar, 'upside_down', false,
                                           class: "radio_button" %>

      <%= label_tag :rotate_avatar_upside_down,
                    class: "radio_button_label" do %>
        <div class = "radio_button_image">
        </div>
        <div class = "radio_button_text">
          <%= t(:turn_upside_down) %>
        </div>
      <% end %>
                                    
    </div>

    <%= f.label :avatar, t(:upload_new_avatar),
                         class: "upload_label" %>
    <%= f.file_field :avatar, accept: 'image/jpeg, image/gif, image/png',
                              class: "upload_field" %>
  </div>

  <%= f.label :name, t(:name), class: "label" %>
  <%= f.text_field :name, class: "text_field" %>

  <%= f.label :email, t(:email), class: "label" %>
  <%= f.email_field :email, class: "text_field" %>

  <%= f.label :password, t(:password), class: "label" %>
  <%= f.password_field :password, class: "text_field" %>

  <%= f.label :password_confirmation, t(:password_confirmation),
                                      class: "label" %>
  <%= f.password_field :password_confirmation, class: "text_field" %>

  <%= f.submit t(:update_profile), class: "button_submit" %>

<% end %>

app/views/humans/index.html.erb
<div class="numbered">
  <% will_be_numbered(humans_path, @humans[:pages]) %>
</div>
<br>

<% if @humans[:objects] %>
  <% @humans[:objects].each do |human| %>

    <div class = "human_wrapper">

      <div class = "human_avatar_block">
        <%= link_to(image_tag(avatar_path(human.id),
                    class: "human_avatar"),
                    human) %>
      </div>

      <div class = "human_name_block">
        <p class = "human_name">
          <%= human.name %>
        </p>
      </div>

      <% if current_human == human || current_human.admin? %>
        <div class = "human_edit">
          <%= link_to t(:edit), edit_human_path(human.id),
                                class: "small_link" %>
        </div>
      <% end %>

      <% if current_human.admin? %>
        <div class = "human_delete">
          <%= link_to t(:delete), human,
                                  method: :delete,
                                  data: { confirm: t(:delete_confirmation) },
                                  class: "small_link" %>
        </div>
      <% end %>

    </div>
  <% end %>
<% end %>
<script type="text/javascript">
  PreLoader("human_avatar");
</script>

app/views/humans/new.html.erb
<%= form_for(@human, html: {class: "plain_form"}) do |f| %>

  <%= render partial: 'shared/form_errors', locals: { object: @human } %>

  <%= f.label :name, class: "label" %>
  <%= f.text_field :name, class: "text_field" %>

  <%= f.label :email, class: "label" %>
  <%= f.email_field :email, class: "text_field" %>

  <%= f.label :password, class: "label" %>
  <%= f.password_field :password, class: "text_field" %>

  <%= f.label :password_confirmation, class: "label" %>
  <%= f.password_field :password_confirmation, class: "text_field" %>

  <%= f.submit t(:create_profile), class: "button_submit" %>

<% end %>

app/views/humans/show.html.erb
<div class = "human_center_align">
  <div class = "human_wrapper">

    <div class = "human_avatar_block">
      <%= image_tag avatar_path(@human.id), class: "human_avatar" %>
    </div>

    <div class = "human_name_block">
      <p class = "human_name">
        <%= @human.name %>
        <br>
        <%= @human.email %>
      </p>
    </div>

    <% if current_human == @human || current_human.admin? %>
      <div class = "human_edit">
        <%= link_to t(:edit), edit_human_path(@human),
                              class: "small_link" %>
      </div>
    <% end %>

  </div>
</div>