config/routes.rb
Rails.application.routes.draw do

  # navigation
  root 'navigation#homepage'

  scope "/:locale" do
    get 'questions' => 'navigation#questions'

    # for activation
    get 'account_activation/:token/activate', to: 'access#account_activation',
                                              as: 'activation'
    get 'activation_form', to: 'access#activation_form', as: 'activation_form'
    post 'create_activation', to: 'access#create_activation',
                              as: 'create_activation'

    # for password reset
    get 'account_activation/:token/reset', to: 'access#reset_password',
                                              as: 'reset_password'
    get 'reset_password_form', to: 'access#reset_password_form',
                               as: 'reset_password_form'
    post 'create_reset_link', to: 'access#create_reset_link',
                              as: 'create_reset_link'

    # for login
    get 'login_form' => 'access#login_form'
    post 'create_session' => 'access#create_session'
    delete 'destroy_session' => 'access#destroy_session'

    # for sending photos
    get 'photo/:id/:type/get', to: 'photos#send_photo', as: 'get_photo'
	  get 'humans/:id/avatar', to: 'humans#send_avatar', as: 'avatar'

    resources :humans

    resources :photo_galleries, shallow: true do
      resources :photos, except: :show
    end

    resources :photos, only: :show do
      resources :comments, only: [:create]
    end

    resources :comments, only: [:destroy]
	  resources :chats, only: [:show, :index, :create]

  end

end

app/models/photo.rb
# Just a photo
class Photo < ActiveRecord::Base
  include SharedModelMethods
  before_destroy :delete_photo
  belongs_to :photo_gallery
  has_many :comments, dependent: :destroy

  validates :name, length: { maximum: 222 }

  def delete_photo
    FileUtils.rm_f "#{Rails.root}#{path}"
    FileUtils.rm_f "#{Rails.root}" \
      "#{path[%r{\A.*/}]}resized_#{path[%r{[^/]*\z}]}"
    return unless Dir["#{Rails.root}#{path[%r{\A.*/}]}*"].empty?
    FileUtils.rmdir "#{Rails.root}#{path[%r{\A.*/}]}"
  end
end

app/controllers/photos_controller.rb
# Just a photos controller
class PhotosController < ApplicationController
  before_action :human_only

  def send_photo
    if @photo = Photo.find_by('id = ?', params[:id]) # ok
      path = @photo.path
    else
      path = '/public/Default_Cover/Default_Cover.png'
    end

    if path && photo_path = check_path(params[:type], path) # ok
      send_file Rails.root.to_s + photo_path, x_sendfile: true
    else
      flash[:alert] = t(:no_photo)
      redirect_to root_path
    end
  end

  def show
    if @photo = Photo.find_by('id = ?', params[:id]) # ok
      @comment = Comment.new
      @comments = @photo.comments
      if @photo_gallery = PhotoGallery.find_by(id: @photo.photo_gallery_id)
        @human = @photo_gallery.human
      end
    else
      flash[:alert] = t(:no_photo)
      redirect_to root_path
    end
  end

  def index
    if @photo_gallery = PhotoGallery
                        .find_by('id = ?', params[:photo_gallery_id]) # ok
      @photos = @photo_gallery.photos.numbering(params[:list]) # ok
      @human = @photo_gallery.human
    else
      flash[:alert] = t(:no_photo_gallery)
      redirect_to root_path
    end
  end

  def new
    @photo_gallery = PhotoGallery
                     .find_by('id = ?', params[:photo_gallery_id]) # ok
    if @photo_gallery && (@photo_gallery.human == current_human ||
                          current_human.admin?)
      @photo = Photo.new
    else
      flash[:alert] = t(:restrict_to_add_photo)
      redirect_to root_path
    end
  end

  def create
    @current_gallery = PhotoGallery
                       .find_by('id = ?', params[:photo_gallery_id]) # ok

    if @current_gallery && (current_human == @current_gallery.human ||
                            current_human.admin?)

      if params[:uploading] &&
         params[:uploading].is_a?(Hash) &&
         params[:uploading][:files] &&
         params[:uploading][:files].respond_to?(:each)

        files = params[:uploading][:files] # ok

        # Folder path for storing files
        dir = "private/photo_galleries/human_#{current_human.id}/" \
              "photo_gallery_#{@current_gallery.id}/"
        @json = []

        files.each do |file|
          # Checking content of 'file' variable
          if file.respond_to?(:content_type) &&
             file.respond_to?(:original_filename)

            file_name = file.original_filename # ok

            # Check file type
            if file.content_type == 'image/jpeg' ||
               file.content_type == 'image/png'

              # If file has been handled - creating photo object
              if file_path_for_db = handle_file(file, dir) # ok
                @photo = @current_gallery.photos.build(path: file_path_for_db)
                @photo.save # Not user problem!
                @json << { id: @photo.id }
              else
                # add error message to @json and Flash
                @json << add_error(file_name) # questionable place
              end
            else
              # add error message to @json and Flash
              @json << add_error(file_name) # questionable place
            end
          end
        end
        # sending answer
        if request.xhr?
          render json: @json
        else
          redirect_to photo_gallery_photos_path(@current_gallery.id)
        end
      else
        # sending answer if wrong attributes
        if request.xhr?
          render json: { message: t(:wrong_data) }
        else
          flash[:alert] = t(:wrong_data)
          redirect_to root_path
        end
      end
    else
      # sending answer if no access
      if request.xhr?
        render json: { message: t(:restrict_to_add_photo) }
      else
        flash[:alert] = t(:restrict_to_add_photo)
        redirect_to root_path
      end
    end
  end

  def edit
    if @photo = Photo.find_by('id = ?', params[:id]) # ok
      @current_gallery = @photo.photo_gallery

      if @current_gallery && (@current_gallery.human == current_human ||
                              current_human.admin?)
        render 'edit'
      else
        flash[:alert] = t(:restrict_to_change_photo)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:no_photo)
      redirect_to root_path
    end
  end

  def update
    if @photo = Photo.find_by('id = ?', params[:id]) # ok
      @current_gallery = @photo.photo_gallery

      if @current_gallery && (@current_gallery.human == current_human ||
                              current_human.admin?)
        # Photo rotation
        rotation = params[:rotation] # ok
        if rotation == 'left' || rotation == 'right'

          photo_rotation photo_path: @photo.path, rotation: rotation

          if request.xhr?
            render json: { status: 'OK' }
          else
            render 'edit'
          end
        else
          # Update attributes
          if params[:make_me_cover] == '1' # ok
            @current_gallery.cover = @photo.id
            @current_gallery.save # Not user problem!
          end
          @photo.update_attributes(attributes) # ok

          # Check errors
          if @photo.errors.any?
            if request.xhr?
              render json: { status: 'BAD', errors: get_errors(@photo) }
            else
              render 'edit'
            end
          else
            if request.xhr?
              render json: { status: 'OK' }
            else
              redirect_to photo_path(@photo.id)
            end
          end
        end
      else
        flash[:alert] = t(:restrict_to_change_photo)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:no_photo)
      redirect_to root_path
    end
  end

  def destroy
    if @photo = Photo.find_by('id = ?', params[:id]) # ok
      @photo_gallery = @photo.photo_gallery
      if @photo_gallery && (@photo_gallery.human == current_human ||
                            current_human.admin?)

        # if has been deleted
        if @photo.destroy
          if request.xhr?
            render json: { status: 'OK', errors: 'NoErrors' }
          else
            flash[:message] = t(:deleted_photo)
            redirect_to photo_gallery_photos_path(@photo_gallery.id)
          end

        # if hasn't been deleted
        else
          if request.xhr?
            render json: { status: 'BAD', errors: get_errors(@photo) }
          else
            flash[:alert] = t(:delete_photo_problem)
            redirect_to photo_gallery_photos_path(@photo_gallery.id)
          end
        end
      else
        flash[:alert] = t(:restrict_to_delete_photo)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:no_photo)
      redirect_to root_path
    end
  end

  private

  def attributes
    if !params[:photo].blank? && params[:photo].is_a?(Hash)
      return params.require(:photo).permit(:name)
    else
      return {}
    end
  end

  def get_errors(object)
    errors = []
    object.errors.full_messages.each do |error|
      errors << error
    end
    errors
  end

  def add_error(filename)
    flash[:alert] ||= []
    flash[:alert] << t(:file) + " '" + filename + # questionable place
      "' " + t(:upload_problem)
    { name: filename, id: 'None' } # questionable place
  end

  def handle_file(file, dir)
    # Creating data for file
    file_name = DateTime.now.strftime('%H%M%S_%d%m%Y') +
                SecureRandom.urlsafe_base64 +
                '.png'

    file_path = Rails.root.join(dir, file_name)
    file_path_resized = Rails.root.join(dir, 'resized_' + file_name)
    file_path_for_db = '/' + dir + file_name

    # Creating new folder if doesn't exist
    unless File.exist?(Rails.root.join(dir))
      FileUtils.mkdir_p(Rails.root.join(dir), mode: 0700)
    end

    # Convert uploaded file to ".png"
    MiniMagick::Tool::Convert.new(false) do |convert|
      convert << file.path # questionable place
      convert << '-resize'
      convert << '800x800'
      convert << '-auto-orient'
      convert << file_path
    end

    # Resizing
    MiniMagick::Tool::Convert.new(false) do |convert|
      convert << file_path # questionable place
      convert << '-resize'
      convert << '300x300'
      convert << file_path_resized
    end

    if File.exist?(file_path)
      return file_path_for_db
    else
      return false
    end
  end

  def photo_rotation(hash = {})
    path1 = hash[:photo_path]
    path2 = path1[%r{\A.*/}] + 'resized_' + path1[%r{[^/]*\z}]
    full_paths = ["#{Rails.root}/#{path1}", "#{Rails.root}/#{path2}"]
    full_paths.each do |path|
      MiniMagick::Tool::Convert.new do |convert|
        convert << path
        convert << '-rotate'
        convert << '90' if hash[:rotation] == 'right'
        convert << '-90' if hash[:rotation] == 'left'
        convert << path
      end
    end
  end

  def check_path(type, path)
    if type == 'resized'
      path[%r{\A.*/}] + 'resized_' + path[%r{[^/]*\z}]
    elsif type == 'full'
      path
    else
      return false
    end
  end
end

app/helpers/photos_helper.rb
# PhotosHelper
module PhotosHelper
end

app/views/photos/edit.html.erb
<div class = "photo_center_align">

  <%= image_tag get_photo_path(@photo.id, 'full'),
                class: "middle_photo", id: "middle_photo" %>

  <div class = "picture_rotation_block">

    <button class = "rotation_button_left" id = "rotation_left">
    </button>

    <button class = "rotation_button_right" id = "rotation_right">
    </button>

  </div>

</div>

<%= form_for(:photo, url: photo_path(@photo.id),
                     method: :patch,
                     html: {class: "plain_form"} ) do |f| %>

  <%= render partial: 'shared/form_errors', locals: { object: @photo } %>

  <%= f.label :name, t(:photo_name), class: "label" %>
  <%= f.text_field :name, class: "text_field" %>

  <%= check_box_tag :make_me_cover, value = "1", checked = false,
                                                 class: "checkbox" %>

  <%= label_tag :make_me_cover, class: "checkbox_label" do %>
    <div class = 'checkbox_image'>
    </div>
    <div class = 'checkbox_text'>
      <%= t(:make_me_cover) %>
    </div>
  <% end %>

  <%= f.submit t(:save), class: "button_submit_for_checkbox" %>

<% end %>

<script type="text/javascript">

  RotationListener("rotation_left",
                   "middle_photo",
                   <%= @photo.id %>,
                   "left",
                   '<%= t(:rotation) %>',
                   '<%= form_authenticity_token %>',
                   '<%= I18n.locale %>');

  RotationListener("rotation_right",
                   "middle_photo",
                   <%= @photo.id %>,
                   "right",
                   '<%= t(:rotation) %>',
                   '<%= form_authenticity_token %>',
                   '<%= I18n.locale %>');

</script>

app/views/photos/index.html.erb
<div class = "title_block">

  <div class = "title_text_block">
    <p class = "title_text">
      <%= @photo_gallery.description %>
    </p>
  </div>

  <div class = "title_human_block">
    <%= link_to "(#{@human.name})", @human, class: "small_link" %>
    <br>
    <% if current_human == @human || current_human.admin? %>
      <%= link_to t(:add_new_photo),
          new_photo_gallery_photo_path(@photo_gallery.id),
          class: "small_link" %>
    <% end %>
  </div>

</div>

<div class="numbered">
  <% will_be_numbered(photo_gallery_photos_path(@photo_gallery.id),
                      @photos[:pages]) %>
</div>

<% if @photos[:objects] %>
  <% @photos[:objects].each do |photo| %>
    <div class = "photo_wrapper">

      <div class = "photo_block">
        <%= link_to(image_tag(get_photo_path(photo.id, 'resized'),
                              class: "resized_photo"),
                    photo_path(photo.id)) %>
      </div>

      <% if current_human == photo.photo_gallery.human ||
                             current_human.admin? %>
        <div class = "photo_edit">
          <%= link_to t(:edit), edit_photo_path(photo.id),
                                class: "small_link" %>
        </div>

        <div class = "photo_delete">
          <%= link_to t(:delete), photo_path(photo.id),
                                  method: :delete,
                                  data: { confirm: t(:delete_confirmation) },
                                  class: "small_link" %>
        </div>
      <% end %>

    </div>
  <% end %>
<% end %>

<script type="text/javascript">
  PreLoader("resized_photo");
</script>

app/views/photos/new.html.erb
<%= form_for(:uploading, url: photo_gallery_photos_path(@photo_gallery.id),
             remote: true,
             html: { multipart: true, id: "Upload_Form", class: "plain_form" }
            ) do |f| %>

  <%= f.label :files, t(:upload_files) %>
  <%= f.file_field :files, id: "uploading_files", multiple: true %>

  <%= f.submit t(:upload), type: "submit", id: "button_submit_plain",
                                           class: "button_submit" %>

<% end %>

<div id="ForProgressBar">
</div>

<script type="text/javascript">


  var button = document.createElement("button");
  var photos = "";
  var xhrResponse = [];

//----------------------- Good button for good browsers ------------------------


  if (window.navigator.userAgent.indexOf("MSIE") < 0) {

    var buttonPlain = document.getElementById("button_submit_plain");
    var buttonForGoodBrowsers = document.createElement("button");
    var uploadForm = document.getElementById("Upload_Form");

    buttonPlain.parentNode.removeChild(buttonPlain);
    buttonForGoodBrowsers.className = "button_submit";
    buttonForGoodBrowsers.id = "Upload_Button";
    buttonForGoodBrowsers.type = "button";
    buttonForGoodBrowsers.innerHTML = "<%= t(:upload) %>";
    uploadForm.appendChild(buttonForGoodBrowsers);
    var uploadButton = document.getElementById("Upload_Button");
  }


//----------------------------- Main Functions ---------------------------------



  if (uploadButton) {

    //If button is clicked
    uploadButton.onclick = function() {

      //Uploading files
      var xhr = new XMLHttpRequest();
      UploadFiles("uploading_files", "ForProgressBar", "Upload_Form", xhr);

      xhr.onload = function() {

        //Getting data from server
        photos = JSON.parse(this.responseText);
      
        //Creating form for photos
        photos = CreatePhotoForm(photos, "ForProgressBar", button);

        //Adding listeners for rotation buttons
        for (var i=0; i<photos.length; i++) {
          i2 = photos[i]['id'];

          RotationListener("rotation_left_id_" + i2, 
                           "photo_id_" + i2, 
                           i2, 
                           "left");

          RotationListener("rotation_right_id_" + i2, 
                           "photo_id_" + i2, 
                           i2, 
                           "right");
          DeleteListener("delete_id_" + i2, 
                           "upload_block_id_" + i2, 
                           photos[i],
                           photos);
        }
      }
    }
  }

  //If button is clicked sending data to server
  button.onclick = function() {

    //Hide button
    button.parentNode.removeChild(button);

    //Sending filled form
    SendFilledForms(photos, xhrResponse);

    //Getting answer from server
    var CheckResponse = setInterval(function() {
      if (xhrResponse.length == photos.length) {
        clearInterval(CheckResponse);
        var i2=0;
        for (var i=0; i<xhrResponse.length; i++) {
          if (xhrResponse[i].status == "OK") {
            i2++;
          }
        }
        //If no errors - redirect to photo gallery else return a button
        if (i2==xhrResponse.length) {
          window.location = "<%=photo_gallery_photos_path(@photo_gallery.id)%>";
        }
        else {
          document.getElementById("ForProgressBar").appendChild(button);
          xhrResponse = [];
        }
      }
    }, 1000);
  }

//------------------------------- Functions ------------------------------------

  function DeleteListener(buttonId, blockId, object, photos) {
    document.getElementById(buttonId).onclick = function () {
      var xhr = new XMLHttpRequest();
      xhr.open("delete", "/<%= I18n.locale %>/photos/" + object['id'], true);
      xhr.setRequestHeader('X-CSRF-Token', '<%= form_authenticity_token %>');
      xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
      xhr.send();
      xhr.onload = function() {
        var data = JSON.parse(this.responseText);
        if (data.status == "OK") {
          //deleting block
          var block = document.getElementById(blockId);
          block.parentNode.removeChild(block);
          photos.splice(photos.indexOf(object), 1);
        }
      }
    }
  }

  function RotationListener(buttonId, photoId, objectId, direction) {
    document.getElementById(buttonId).onclick = function () {
      var photo =  document.getElementById(photoId);
      if (photo) {
        var xhr = new XMLHttpRequest();
        var  form = new FormData();

        //Temporary photo while rotation
        var photoParentNode = photo.parentNode;
        var temporaryItem = document.createElement("div");
        temporaryItem.className = "upload_InProgress";
        temporaryItem.innerHTML = "<div class = 'upload_InProgress_text'>" +
                                  "<%= t(:rotation) %>" +
                                  "</div>";
        photo.parentNode.removeChild(photo);
        photoParentNode.appendChild(temporaryItem);

        form.append("rotation", direction);
        xhr.open("PATCH", "/<%= I18n.locale %>/photos/" + objectId, true);
        xhr.setRequestHeader('X-CSRF-Token', '<%= form_authenticity_token %>');
        xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        xhr.send(form);
        xhr.onload = function() {
          temporaryItem.parentNode.removeChild(temporaryItem);
          photoParentNode.appendChild(photo);
          photo.src = photo.src + "?" + new Date().getTime();
        }
      }
    }
  }

  function UploadFiles(inputId, outputPlace, formForHiding, xhr) {

    var input = document.getElementById(inputId);
    if (input.files.length != 0) {
      var output = document.getElementById(outputPlace);
      var form = new FormData();

      //Creating Progress bar
      var divProgressBar = document.createElement("div");
      divProgressBar.className = "Progress_bar";
      var divInformationBlock = document.createElement("div");
      divInformationBlock.className = "Progress_Information";
      var divProgressBlock = document.createElement("div");
      divProgressBlock.className = "Progress_block";
      var divProgress = document.createElement("div");
      divProgress.className = "Progress";
      var divProgressStatus = document.createElement("div");
      divProgressStatus.className = "Progress_status";
      output.appendChild(divProgressBar);
      divProgressBar.appendChild(divInformationBlock);
      divProgressBar.appendChild(divProgressBlock);
      divProgressBlock.appendChild(divProgressStatus);
      divProgressBlock.appendChild(divProgress);

      //Selecting data from html form to xhr form for sending
      for (var i=0; i<input.files.length; i++) {
        form.append('uploading[files][]', input.files[i]);
      }

      //Hide HTML form
      var uploadForm = document.getElementById(formForHiding);
      uploadForm.parentNode.removeChild(uploadForm);

      //Progress information
      divInformationBlock.innerHTML = "<%= t(:upload_progress) %>";

      //While uploading
      xhr.upload.onprogress = function(event) {
        divProgressStatus.innerHTML = Math.round(event.loaded/event.total*100) +
                                      "%";
        divProgress.style.width = event.loaded/event.total*100 + "%";
      }

      //When upload is finished
      xhr.upload.onload = function(event) {
        divInformationBlock.innerHTML = "<%= t(:uploading_complete) %>";
        divProgressStatus.innerHTML = Math.round(event.loaded/event.total*100) +
                                      '%';
        divProgress.style.width = event.loaded/event.total*100 + "%";
      }

      //If errors
      xhr.upload.onerror = function() {
        divProgressStatus.innerHTML = "<%= t(:uploading_problem) %>";
      }

      //Send request
      xhr.open("POST", "<%=photo_gallery_photos_path(@photo_gallery.id)%>",
                       true);
      xhr.setRequestHeader('X-CSRF-Token', '<%= form_authenticity_token %>');
      xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
      xhr.send(form);
    }
  }

  //Creating form for photos
  function CreatePhotoForm(photos, outputPlace, button) {
    var output = document.getElementById(outputPlace);

    //Clear output
    while (output.firstChild) {
      output.removeChild(output.firstChild);
    }

    var i2=0;
    var photos2=[];
    for (var i=0; i<photos.length; i++) {
      if (photos[i]['id'] != "None") {
        photos2[i2] = photos[i];
        i2++;
        var div = document.createElement("div");
        div.className = "upload_block";
        div.id = "upload_block_id_" + photos[i]['id'];
        div.innerHTML = "<div class = 'upload_picture_block'>" +
                        "<img src='/" +
                        "<%= I18n.locale %>" +
                        "/photo/" + photos[i]['id'] + "/resized/get'" +
                        " class = 'upload_picture' " +
                        "id = 'photo_id_" + photos[i]['id'] + "'>" +
                        "</img></div>" +
                        "<div class = 'upload_picture_rotation_block'>" +
                        "<button class = 'rotation_button_left' " + 
                        "id = 'rotation_left_id_" + photos[i]['id'] + "'>" +
//                        "turn left" +
                        "</button>" +

                        "<button class = 'delete_button' " + 
                        "id = 'delete_id_" + photos[i]['id'] + "'>" +
//                        "delete" +
                        "</button>" +

                        "<button class = 'rotation_button_right' " + 
                        "id = 'rotation_right_id_" + photos[i]['id'] + "'>" +
//                        "turn right" +
                        "</button>" +
                        "</div>" +
                        "<div class = 'upload_picture_information_block'>" +
                        "<p class = 'upload_picture_information' " +
                        "id = 'information_id_" + photos[i]['id'] + "'>" + 
                        "<%= t(:photo_name) %>" +
                        "</p>" +
                        "</div>" +
                        "<div class = 'upload_picture_text_area_block'>" +
                        "<textarea class = 'upload_picture_text_area' " +
                        "id = 'id_" + photos[i]['id'] + "'>" +
                        "</textarea>" +
                        "</div>";
        output.appendChild(div);
      }
    }
    if (photos.length != photos2.length) {
        var div2 = document.createElement("div");
        div2.className = "upload_block";
        div2.innerHTML = "<div class = 'upload_picture_errors'>" +
                         "<%= t(:uploading_errors) %>" +
                         "</div>";
        output.appendChild(div2);
    }
    button.className = "upload_picture_button";
    button.innerHTML = "<%= t(:confirm) %>";
    output.appendChild(button);
    return photos2;
  }

  function SendFilledForms(photos, xhrResponse) {
    var xhr = [];
    for (var i=0; i<photos.length; i++) {
      xhr[i] = new XMLHttpRequest();
      var form = new FormData();
      form.append("photo[name]", document.
                                 getElementById("id_" + photos[i]['id']).value);
      xhr[i].open("PATCH", "/<%= I18n.locale %>/photos/" + photos[i]['id'], true);
      xhr[i].setRequestHeader('X-CSRF-Token', '<%= form_authenticity_token %>');
      xhr[i].setRequestHeader('X-Requested-With', 'XMLHttpRequest');
      xhr[i].send(form);
      xhr[i].onload = function() {
        var status = document.getElementById("information_id_" +
                                             photos[xhr.indexOf(this)]['id']);
        var data = JSON.parse(this.responseText);
        xhrResponse[xhr.indexOf(this)] = data;
        if (data.status == "BAD") {
          //status.style.color = "red";
          status.innerHTML = "";
          for (i=0; i<data.errors.length; i++) {
            var div = document.createElement("div");
            var alert = document.createTextNode(data.errors[i]);
            div.className = 'AlertInformation';
            div.appendChild(alert);
            status.appendChild(div);
          }
        }
        else if (data.status == "OK") {
          status.style.color = "green";
          status.innerHTML = "OK";
        }
      }
    }
  }
</script>

app/views/photos/show.html.erb
<div class = "title_block">

  <div class = "title_text_block">
    <p class = "title_text">
      <%= link_to "#{@photo_gallery.description}",
                  photo_gallery_photos_path(@photo_gallery.id),
                  class: "title_link" %>
    </p>
  </div>

  <div class = "title_human_block">
    <%= link_to "(#{@human.name})", @human, class: "small_link" %>
  </div>

</div>

<div class = "photo_center_align">

  <div class = "photo_block" id = "photo_block_id">
  </div>

  <div class = "photo_description">
    <%= @photo.name %>
  </div>

  <% if current_human == @photo.photo_gallery.human || current_human.admin? %>
    <div class = "photo_edit">
      <%= link_to t(:edit), edit_photo_path(@photo.id),
                            class: "small_link" %>
    </div>

    <div class = "photo_delete">
      <%= link_to t(:delete), photo_path(@photo.id),
                              method: :delete,
                              data: { confirm: t(:delete_confirmation) },
                              class: "small_link" %>
    </div>
  <% end %>

</div>

<%= form_for(@comment, url: photo_comments_path(@photo.id),
                       html: {class: "comment_form"}) do |f| %>

  <%= f.label :text, t(:write_comment), class: "comment_label" %>

  <%= f.submit t(:send), class: "comment_button_submit",
                         id: "comment_button_submit" %>

  <div class = "comment_text_area_wrapper">
    <%= f.text_area :text, class: "comment_text_area",
                           id: "comment_text_area" %>
  </div>

<% end %>

<% if @comments %>
  <% @comments.each do |comment| %>
    <div class = "comments_center_align">

      <div class = "comments_human_block">

        <div class = "comments_avatar_block">
          <%= image_tag avatar_path(comment.human.id),
                        class: "comments_avatar" %>
        </div>

        <div class = "human_name">
          <%= comment.human.name %>
        </div>

        <div class = "comments_date">
          <%= comment.created_at.strftime("%H:%M:%S %d.%m.%Y") %>
        </div>

        <% if current_human == comment.human || current_human.admin? %>
          <div class = "comments_delete">
            <%= link_to t(:delete), comment_path(comment.id),
                                    method: :delete,
                                    data: { confirm: t(:delete_confirmation) },
                                    class: "small_link" %>
          </div>
        <% end %>

      </div>

      <div class = "comments_text_block">
        <div class = "comments_text">
          <%= comment.text %>
        </div>
      </div>

    </div>
  <% end %>
<% end %>
<a name='bottom'> </a>
<script type="text/javascript">

// These functions live in assets
  EnterSubmitComments();
  FullPhotoPreLoader("<%= get_photo_path(@photo.id, 'full') %>",
                     "photo_block_id",
                     "<%= t(:image_preload) %>");

</script>