config/routes.rb
Rails.application.routes.draw do

  # navigation
  root 'navigation#homepage'

  scope "/:locale" do
    get 'questions' => 'navigation#questions'

    # for activation
    get 'account_activation/:token/activate', to: 'access#account_activation',
                                              as: 'activation'
    get 'activation_form', to: 'access#activation_form', as: 'activation_form'
    post 'create_activation', to: 'access#create_activation',
                              as: 'create_activation'

    # for password reset
    get 'account_activation/:token/reset', to: 'access#reset_password',
                                              as: 'reset_password'
    get 'reset_password_form', to: 'access#reset_password_form',
                               as: 'reset_password_form'
    post 'create_reset_link', to: 'access#create_reset_link',
                              as: 'create_reset_link'

    # for login
    get 'login_form' => 'access#login_form'
    post 'create_session' => 'access#create_session'
    delete 'destroy_session' => 'access#destroy_session'

    # for sending photos
    get 'photo/:id/:type/get', to: 'photos#send_photo', as: 'get_photo'
	  get 'humans/:id/avatar', to: 'humans#send_avatar', as: 'avatar'

    resources :humans

    resources :photo_galleries, shallow: true do
      resources :photos, except: :show
    end

    resources :photos, only: :show do
      resources :comments, only: [:create]
    end

    resources :comments, only: [:destroy]
	  resources :chats, only: [:show, :index, :create]

  end

end

app/models/photo_gallery.rb
# Just a photo gallery
class PhotoGallery < ActiveRecord::Base
  include SharedModelMethods

  belongs_to :human
  has_many :photos, dependent: :destroy

  validates :description, presence: true, length: { maximum:  150 }
end

app/controllers/photo_galleries_controller.rb
# Just a photo galleries controller
class PhotoGalleriesController < ApplicationController
  before_action :human_only

  def new
    @photo_gallery = PhotoGallery.new
  end

  def create
    if attributes
      cover = 'default'
      @photo_gallery = current_human.photo_galleries.build(attributes) # Ok
      if @photo_gallery && @photo_gallery.cover = cover
        if @photo_gallery.save
          redirect_to photo_gallery_photos_path(@photo_gallery.id)
        else
          render 'new'
        end
      end
    else
      flash[:alert] = t(:no_data)
      redirect_to root_path
    end
  end

  def show
    return if @photo_gallery = PhotoGallery.find_by('id = ?', params[:id]) # Ok
    flash[:alert] = t(:no_photo_gallery)
    redirect_to root_path
  end

  def edit
    @photo_gallery = PhotoGallery.find_by('id = ?', params[:id]) # Ok
    if @photo_gallery && (@photo_gallery.human == current_human ||
                                                  current_human.admin?)
      render 'edit'
    else
      flash[:alert] = t(:restrict_to_change_photo_gallery)
      redirect_to root_path
    end
  end

  def update
    @photo_gallery = PhotoGallery.find_by('id = ?', params[:id]) # Ok
    if @photo_gallery && (@photo_gallery.human == current_human ||
                                                  current_human.admin?)
      if attributes
        if @photo_gallery.update_attributes(attributes) # Ok
          redirect_to photo_gallery_path(@photo_gallery.id)
        else
          render 'edit'
        end
      else
        flash[:alert] = t(:no_data)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:restrict_to_change_photo_gallery)
      redirect_to root_path
    end
  end

  def destroy
    @photo_gallery = PhotoGallery.find_by('id = ?', params[:id]) # Ok
    if @photo_gallery && (@photo_gallery.human == current_human ||
                                                  current_human.admin?)
      if @photo_gallery.destroy
        flash[:message] = t(:deleted_photo_gallery)
        redirect_to photo_galleries_path
      else
        redirect_to root_path
      end
    else
      flash[:alert] = t(:restrict_to_delete_photo_gallery)
      redirect_to root_path
    end
  end

  def index
    @photo_gallery = PhotoGallery.numbering(params[:list]) # Ok
  end

  private

  def attributes
    return if params[:photo_gallery].blank? ||
              !params[:photo_gallery].is_a?(Hash)
    params.require(:photo_gallery).permit(:description)
  end
end

app/helpers/photo_galleries_helper.rb
# PhotoGalleriesHelper
module PhotoGalleriesHelper
end

app/views/photo_galleries/edit.html.erb
<%= form_for(:photo_gallery, url: photo_gallery_path, method: :patch) do |f| %>
  <%= render partial: 'shared/form_errors',
             locals: { object: @photo_gallery } %>

  <%= f.label :description, t(:description), class: "label" %>
  <%= f.text_field :description, class: "text_field" %>
  <%= f.submit t(:save), class: "button_submit" %>

<% end %>

app/views/photo_galleries/index.html.erb
<div class = "title_block">
  <%= link_to t(:create_gallery), new_photo_gallery_path,
                                  class: "title_link_small" %>
</div>

<div class="numbered">
  <% will_be_numbered(photo_galleries_path, @photo_gallery[:pages]) %>
</div>

<% if @photo_gallery[:objects] %>
  <% @photo_gallery[:objects].each do |gallery| %>
    <div class = "photo_gallery_wrapper">

      <div class = "photo_gallery_cover_block">
        <%= link_to(image_tag(get_photo_path(gallery.cover, 'resized'),
                              class: 'photo_gallery_cover'),
                    photo_gallery_photos_path(gallery.id)) %>
      </div>

      <div class = "photo_gallery_description_block">
        <p class = "photo_gallery_description">
          <%= gallery.description %>
        </p>
      </div>

      <% if current_human == gallery.human || current_human.admin? %>
        <div class = "photo_gallery_edit">
          <%= link_to t(:edit), edit_photo_gallery_path(gallery.id),
                                class: "small_link" %>
        </div>

        <div class = "photo_gallery_delete">
          <%= link_to t(:delete), photo_gallery_path(gallery.id),
                                  method: :delete,
                                  data: { confirm: t(:delete_confirmation) },
                                  class: "small_link" %>
        </div>
      <% end %>

    </div>
  <% end %>
<% end %>
<script type="text/javascript">
  PreLoader("photo_gallery_cover");
</script>

app/views/photo_galleries/new.html.erb
<%= form_for(:photo_gallery, url: photo_galleries_path) do |f| %>
  <%= render partial: 'shared/form_errors',
             locals: { object: @photo_gallery } %>

  <%= f.label :description, t(:description), class: "label" %>
  <%= f.text_field :description, class: "text_field" %>
  <%= f.submit t(:create), class: "button_submit" %>

<% end %>

app/views/photo_galleries/show.html.erb
<div class = photo_gallery >

  <div class = cover >
    <%= link_to(image_tag(get_photo_path(@photo_gallery.cover, 'resized'),
                          class: 'photo_gallery_cover'),
                photo_gallery_photos_path(@photo_gallery.id)) %>
  </div>

  <% if current_human == @photo_gallery.human || current_human.admin? %>
    <div class = "photo_gallery_edit">
      <%= link_to t(:edit), edit_photo_gallery_path(@photo_gallery.id),
                            class: "small_link" %>
    </div>

    <div class = "photo_gallery_delete">
      <%= link_to t(:delete), photo_gallery_path(@photo_gallery.id),
                              method: :delete,
                              data: { confirm: t(:delete_confirmation) },
                              class: "small_link" %>
    </div>
  <% end %>

  <div class = description >
    <%= @photo_gallery.description %>
  </div>

</div>