config/routes.rb
Rails.application.routes.draw do

  # navigation
  root 'navigation#homepage'

  scope "/:locale" do
    get 'questions' => 'navigation#questions'

    # for activation
    get 'account_activation/:token/activate', to: 'access#account_activation',
                                              as: 'activation'
    get 'activation_form', to: 'access#activation_form', as: 'activation_form'
    post 'create_activation', to: 'access#create_activation',
                              as: 'create_activation'

    # for password reset
    get 'account_activation/:token/reset', to: 'access#reset_password',
                                              as: 'reset_password'
    get 'reset_password_form', to: 'access#reset_password_form',
                               as: 'reset_password_form'
    post 'create_reset_link', to: 'access#create_reset_link',
                              as: 'create_reset_link'

    # for login
    get 'login_form' => 'access#login_form'
    post 'create_session' => 'access#create_session'
    delete 'destroy_session' => 'access#destroy_session'

    # for sending photos
    get 'photo/:id/:type/get', to: 'photos#send_photo', as: 'get_photo'
	  get 'humans/:id/avatar', to: 'humans#send_avatar', as: 'avatar'

    resources :humans

    resources :photo_galleries, shallow: true do
      resources :photos, except: :show
    end

    resources :photos, only: :show do
      resources :comments, only: [:create]
    end

    resources :comments, only: [:destroy]
	  resources :chats, only: [:show, :index, :create]

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(:main_title) %></title>
      <%= stylesheet_link_tag 'application', media: 'all',
                              'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application',
                                 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
      <p class='MainHeader'><%= t(:main_title) %></p>
      <% if request.env['PATH_INFO'] != "/" %>
        <nav class='navigation'>
          <div class = 'navigation_block'>
            <%= link_to t(:home_page), root_path, class: "header_link" %>
            <%= link_to t(:chat), chats_path + "#bottom",
                                  class: "header_link" %>
            <%= link_to t(:humans), humans_path, class: "header_link" %>
            <%= link_to t(:photo_galleries), photo_galleries_path,
                                             class: "header_link" %>
            <%= link_to t(:questions), questions_path, class: "header_link" %>

            <div class="language_block">
              <div class="language_cover">

                  <div class="language_title">
                    <%= t(:language) %>
                  </div>

                  <div class="item">
                    <%= link_to t(:english), url_for(language: "en"),
                                      class: "submenu_link" %>
                  </div>

                  <div class="item">
                    <%= link_to t(:russian), url_for(language: "ru"),
                                      class: "submenu_link" %>
                  </div>

              </div>
            </div>

            <% if human_inside? %>
              <%= link_to t(:log_out), destroy_session_path,
                                       method: "delete", class: "header_link" %>
            <% else %>
              <%= link_to t(:log_in), login_form_path, class: "header_link" %>
              <%= link_to t(:create_profile), new_human_path,
                                              class: "header_link" %>
            <% end %>

          </div>
        </nav>
      <% end %>
    </header>

    <div class = 'InformationBlock' id = 'InformationBlock'>
      <% flash.each do |key, value| %>
        <% if key == 'alert' %>
          <div class = 'AlertInformation'>
            <%  if value.kind_of?(Array) %>
              <% value.each do |x| %>
                <%= x %>
                <br>
              <% end %>
            <% else %>
              <%= value %>
            <% end %>
          </div>
        <% elsif key == 'message' %>
          <div class = 'CommonInformation'>
            <%= value %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="wrapper">
      <%= yield %>
    </div>

    <footer>
      <div class = 'FooterText'>
        <%= t(:сreated_by) %>
      </div>
    </footer>

  </body>
</html>